# 禁用 RESTEasy 重复注册警告
org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.level = SEVERE
org.jboss.resteasy.level = SEVERE

# 控制台处理器
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
